// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package config

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("./../../secrets", "secrets.yaml.template", "\"bmF0c1VybDogIiR7TkFUU19VUkx9Igpmcm9udFVybDogIiR7RlJPTlRfVVJMfSIKYXBpVXJsOiAiJHtBUElfVVJMfSIK\"")
	packr.PackJSONBytes("./../../secrets", "staging.yaml", "\"bmF0c1VybDogIm5hdHM6Ly9hZG1pbjpzZWN1cmVhcGlnb25uYWtpY2t5b3VyYXNzZXNAYXBpc3RhZ2luZy5zZWN1cmVhcGkuZGV2OjQyMjIiCmZyb250VXJsOiAiaHR0cHM6Ly9zdGFnaW5nLnNlY3VyZWFwaS5kZXYiCmFwaVVybDogImh0dHBzOi8vYXBpc3RhZ2luZy5zZWN1cmVhcGkuZGV2Igo=\"")
}
