// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package config

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("./../../secrets", "secrets.yaml.template", "\"bmF0c1VybDogIiR7TkFUU19VUkx9Igpmcm9udFVybDogIiR7RlJPTlRfVVJMfSIKYXBpVXJsOiAiJHtBUElfVVJMfSIK\"")
	packr.PackJSONBytes("./../../secrets", "staging.yaml", "\"bmF0c1VybDogIm5hdHM6Ly9vdHRlcmx5LXNlY3VyZTo0NmFhOWE4YmJiM2M0NzQzMDJiYkAzNS4xOTUuMTQ4LjI0OTo0MjIyIgpmcm9udFVybDogImh0dHBzOi8vYXBwLnNlY3VyZWFwaS5kZXYiCmFwaVVybDogImh0dHBzOi8vYXBpLnNlY3VyZWFwaS5kZXYiCg==\"")
}
