name: Tests
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12.8
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.8
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod vendor

    - name: Build
      run: |
        echo $GOPATH
        go get github.com/gobuffalo/packr/packr
        packr
        make build-local
        packr clean
    - name: Test
      run: make coverage
